# Generated by Django 2.1.5 on 2019-03-09 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='info_chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=200)),
                ('sig_en', models.CharField(max_length=200)),
                ('sig_es', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
    ]
