# Generated by Django 2.1.5 on 2019-03-09 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='info_chart',
            name='concept_number',
            field=models.IntegerField(default=0),
        ),
    ]
