# Generated by Django 2.1.5 on 2019-03-09 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_info_chart_concept_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='info_chart',
            name='capa',
            field=models.CharField(default='NA', max_length=200),
        ),
        migrations.AddField(
            model_name='info_chart',
            name='puerto',
            field=models.CharField(default='NA', max_length=200),
        ),
    ]
